name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: 1
      PYTHONPATH: ./src
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install package editable
        run: |
          pip install -e .
      - name: Show Python info
        run: |
          python -V
          python -c "import sys; print('PYTHONPATH entries:', [p for p in sys.path if p])"
          pip list
      - name: Run tests
        run: |
          pytest -q
